pub use effigy_manifest::TASK_MANIFEST_FILE;

pub(super) const DEFAULT_GOD_FILES_WARN: usize = 250;
pub(super) const DEFAULT_GOD_FILES_HIGH: usize = 400;
pub(super) const DEFAULT_GOD_FILES_CRITICAL: usize = 700;
pub(super) const DEFAULT_DUPLICATE_BLOCKS_WARN: usize = 20;
pub(super) const DEFAULT_DUPLICATE_BLOCKS_HIGH: usize = 40;
pub(super) const DEFAULT_DUPLICATE_BLOCKS_CRITICAL: usize = 80;
pub(super) const DEFAULT_DUPLICATE_BLOCKS_MIN_OCCURRENCES: usize = 2;
pub(super) const DEFAULT_COMMENT_RATIO_WARN: f64 = 1.5;
pub(super) const DEFAULT_COMMENT_RATIO_HIGH: f64 = 2.0;
pub(super) const DEFAULT_COMMENT_RATIO_CRITICAL: f64 = 3.0;
pub(super) const DEFAULT_COMMENT_RATIO_MIN_CODE_LINES: usize = 20;
pub(super) const DEFAULT_GENERATED_ASSETS_WARN_BYTES: usize = 1_000_000;
pub(super) const DEFAULT_GENERATED_ASSETS_HIGH_BYTES: usize = 5_000_000;
pub(super) const DEFAULT_GENERATED_ASSETS_CRITICAL_BYTES: usize = 20_000_000;
pub(super) const DEFAULT_GENERATED_IN_SRC_WARN_BYTES: usize = 1;
pub(super) const DEFAULT_GENERATED_IN_SRC_HIGH_BYTES: usize = 20_000;
pub(super) const DEFAULT_GENERATED_IN_SRC_CRITICAL_BYTES: usize = 200_000;
pub(super) const DEFAULT_GENERATED_IN_SRC_SOURCE_ROOTS: &[&str] = &[
    "src/**",
    "app/**",
    "lib/**",
    "crates/**",
    "packages/*/src/**",
    "services/*/src/**",
];
pub(super) const DEFAULT_ATTENTION_MARKER_WARNING: &[&str] = &[
    "TODO",
    "@TODO",
    "REVIEW",
    "NOTE",
    "placeholder",
    "later",
    "stub",
];
pub(super) const DEFAULT_ATTENTION_MARKER_HIGH: &[&str] = &[
    "FIXME",
    "XXX",
    "HACK",
    "@deprecated",
    "deprecated",
    "workaround",
    "tech debt",
];
pub(super) const DEFAULT_ATTENTION_MARKER_CRITICAL: &[&str] =
    &["BUG", "SECURITY", "remove before release"];
pub(super) const DEFAULT_STALE_SUPPRESSION_WARNING: &[&str] = &[
    "@ts-ignore",
    "@ts-expect-error",
    "type: ignore",
    "eslint-disable-next-line",
];
pub(super) const DEFAULT_STALE_SUPPRESSION_HIGH: &[&str] = &[
    "#[allow(",
    "#[expect(",
    "rubocop:disable",
    "swiftlint:disable",
    "prettier-ignore",
    "stylelint-disable",
];
pub(super) const DEFAULT_STALE_SUPPRESSION_CRITICAL: &[&str] = &[
    "nolint",
    "#[allow(warnings)]",
    "shellcheck disable=",
    "eslint-disable",
    "fmt: off",
];

pub(super) const DEFAULT_EXCLUDED_DIRS: &[&str] = &[
    ".git",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".yarn",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "target",
    "vendor",
];

pub(super) const DEFAULT_DOC_DIRS: &[&str] = &["doc", "docs", "documentation"];

pub(super) const DEFAULT_DATA_DIRS: &[&str] = &[
    "benchmark",
    "benchmarks",
    "benches",
    "example",
    "examples",
    "fixture",
    "fixtures",
    "migration",
    "migrations",
    "migrations_dev",
    "seeds",
];

pub(super) const DEFAULT_LOCK_FILE_NAMES: &[&str] = &[
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "cargo.lock",
    "bun.lock",
    "bun.lockb",
    "composer.lock",
];

pub(super) const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "auto-generated",
    "autogenerated",
    "code generated",
    "do not edit",
    "generated by",
];

pub(super) const GENERATED_ASSET_DIRS: &[&str] = &[
    ".next",
    ".nuxt",
    ".parcel-cache",
    ".svelte-kit",
    ".turbo",
    "build",
    "coverage",
    "dist",
    "generated",
    "gen",
    "storybook-static",
    "third_party",
    "vendor",
    "vendors",
];

pub(super) const GENERATED_ASSET_NAME_MARKERS: &[&str] =
    &[".bundle.", ".chunk.", ".generated.", ".map", ".min."];
