[package]
name = "effigy-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "CLI command model and parse grammar for Effigy"

[dependencies]
effigy-core = { path = "../effigy-core" }
effigy-ui = { path = "../effigy-ui" }
crossterm = "0.29"

[lints]
workspace = true
