mod builtin_contract_tests;
mod deploy_tests;
mod direct_task_dispatch_tests;
mod help_tests;
mod init_migrate_tests;
mod parsing_resolution_tests;
mod proof_matrix_tests;
mod task_env_tests;
mod watch_tests;
