use super::super::{HelpRenderer, HelpResult};
use super::shared::{
    option_rows, render_standard_topic_help_spec, text_lines, CommonOption, StandardTopicHelpSpec,
};

pub(crate) fn render_container_help<R: HelpRenderer + ?Sized>(renderer: &mut R) -> HelpResult<()> {
    render_standard_topic_help_spec(renderer, &CONTAINER_HELP)
}

const CONTAINER_HELP: StandardTopicHelpSpec = StandardTopicHelpSpec {
    topic: "container",
    notices: text_lines![
        "Operate one manifest-defined local container environment by name or through the manifest default alias.",
        "V1 stays explicit: host-facing ports and repo-relative mounts are declared in `[containers.*.host]`, and interactive workspace/shell exits now ask whether to bring the environment down, defaulting to yes.",
        "Generated compose also supports bounded `shared = true` backing services for standalone shared databases and caches on the product-owned path.",
        "Mounted sibling repos listed in `systems.<name>.mounts` auto-adopt producer `[isolation].paths` into workspace containers, and the Colima/containerd path now preflights oversized mount payloads before compose-up.",
        "`container data seed` currently targets the repo default container only and stays on the generated-compose path, while `container data dump` exports logical SQL dumps from generated-compose database services.",
        "`container cache list` inventories purge-safe isolated build caches like Rust `target` and package-manager `node_modules` volumes, including legacy opaque `efv-*` Rust target volumes; use `cache prune --kind rust-target`, not orphan volume cleanup, for Rust target pressure.",
        "`container profile status` reports Colima profile sizing against Effigy's managed targets, `container profile resize` applies managed sizing in place by stopping and restarting the profile, `container profile recreate --disk <GiB> --yes` rebuilds it, and `container profile purge --yes` deletes it without restart.",
        "`container volume list` now follows normal repo scope by default; add `--global` for cross-runtime inventory, use `--dormant` for repo-scoped superseded volumes, and use `--orphans` only with `--global` for true ownerless volumes.",
    ],
    usage: text_lines![
        "effigy local container up [--repo <PATH>] [--attach|--detach] [--json]",
        "effigy local container <NAME> up [--repo <PATH>] [--attach|--detach] [--json]",
        "effigy local container down [--repo <PATH>] [--json]",
        "effigy local container down --global [--json]",
        "effigy local container <NAME> down [--repo <PATH>] [--json]",
        "effigy local container status [--repo <PATH>] [--json]",
        "effigy local container status --global [--json]",
        "effigy local container stats --global [--json]",
        "effigy local container <NAME> status [--repo <PATH>] [--json]",
        "effigy local container volume list [--repo <PATH>] [--dormant] [--json]",
        "effigy local container volume list --global [--orphans] [--json]",
        "effigy local container volume prune [--repo <PATH>] --dormant [--yes] [--json]",
        "effigy local container volume prune --global --orphans [--yes] [--json]",
        "effigy local container profile status [--profile <NAME>] [--json]",
        "effigy local container profile resize [--profile <NAME>] [--json]",
        "effigy local container profile purge [--profile <NAME>] [--yes] [--json]",
        "effigy local container profile recreate [--profile <NAME>] [--disk <GiB>] [--yes] [--json]",
        "effigy local container cache list [--repo <PATH>] [--global] [--project <NAME>] [--kind <KIND>] [--json]",
        "effigy local container cache prune [--repo <PATH>] [--global] [--project <NAME>] [--kind <KIND>] [--yes] [--json]",
        "effigy local container <NAME> cache list [--repo <PATH>] [--json]",
        "effigy local container <NAME> cache prune [--repo <PATH>] [--yes] [--json]",
        "effigy local container data list [--repo <PATH>] [--json]",
        "effigy local container <NAME> data list [--repo <PATH>] [--json]",
        "effigy local container data export <VOLUME> <PATH> [--repo <PATH>] [--json]",
        "effigy local container <NAME> data export <VOLUME> <PATH> [--repo <PATH>] [--json]",
        "effigy local container [<NAME>] data dump [<FILE>|<TARGET>|<TARGET>=<FILE|OCI>]... [--db-dump <FILE>|<TARGET>|<TARGET>=<FILE|OCI>]... [--push] [--repo <PATH>] [--json]",
        "effigy local container data import <VOLUME> <PATH> [--repo <PATH>] [--yes] [--json]",
        "effigy local container <NAME> data import <VOLUME> <PATH> [--repo <PATH>] [--yes] [--json]",
        "effigy local container data pull-production [--repo <PATH>] [--yes] [--json]",
        "effigy local container <NAME> data pull-production [--repo <PATH>] [--yes] [--json]",
        "effigy local container data seed [--db-seed <FILE|OCI>|<TARGET>=<FILE|OCI>]... [--no-prompt] [--yes] [--repo <PATH>] [--json]",
        "effigy local container <NAME> logs [--repo <PATH>] [--service <NAME>] [--follow] [--json]",
        "effigy local container <NAME> shell [--repo <PATH>] [--service <NAME>] [--command <CMD>]",
        "effigy local container <NAME> reset [--repo <PATH>] [--keep-data] [--json]",
        "effigy local container <NAME> eject [--repo <PATH>] [--json]",
        "effigy --json local container up [--repo <PATH>]",
    ],
    leading_common_options: &[CommonOption::Repo],
    options: CONTAINER_OPTIONS,
    trailing_common_options: &[
        CommonOption::Json("Render machine-readable container payloads"),
        CommonOption::Help,
    ],
    examples: text_lines![
        "effigy local container up",
        "effigy local container web up --detach",
        "effigy local container web status",
        "effigy local container down --global",
        "effigy local container status --global",
        "effigy local container stats --global",
        "effigy local container volume list",
        "effigy local container volume list --dormant",
        "effigy local container volume list --repo ~/projects/my-app --dormant",
        "effigy local container volume list --global",
        "effigy local container volume list --global --orphans",
        "effigy local container volume prune --dormant --yes",
        "effigy local container volume prune --global --orphans --yes",
        "effigy local container profile status",
        "effigy local container profile resize",
        "effigy local container profile purge --yes",
        "effigy local container profile recreate --disk 180 --yes",
        "effigy local container cache list",
        "effigy local container cache list --global",
        "effigy local container cache list --project acowtancy-dev",
        "effigy local container cache list --kind rust-target",
        "effigy local container cache prune",
        "effigy local container cache prune --project acowtancy-dev --yes",
        "effigy local container cache prune --kind rust-target --yes",
        "effigy local container cache prune --global --yes",
        "effigy local container web data list",
        "effigy local container web data export fixture-web-dev-db-data ./backup.tar.gz",
        "effigy local container data dump legacy_mysql",
        "effigy local container data dump --db-dump legacy_mysql",
        "effigy local container data dump --db-dump ./latest.sql",
        "effigy local container data dump --db-dump app=./app.sql --db-dump app_test=./app_test.sql",
        "effigy local container data dump --db-dump app=oci://ghcr.io/acme/uat-content:2026-05-07 --push --json",
        "effigy local container web data import fixture-web-dev-db-data ./backup.tar.gz",
        "effigy local container web data pull-production",
        "effigy local container data seed --db-seed legacy_mysql",
        "effigy local container data seed --db-seed ./latest.sql",
        "effigy local container data seed --db-seed app=oci://ghcr.io/acme/private-data:uat",
        "effigy local container data seed --db-seed cbs=./cbs.sql --db-seed cbs-mortcalc=./mortcalc.sql",
        "effigy local container web logs --follow",
        "effigy local container web shell --command \"php artisan tinker\"",
        "effigy local container web reset --keep-data",
        "effigy local container web reset",
        "effigy local container web eject",
    ],
};

const CONTAINER_OPTIONS: &[(&str, &str)] = option_rows![
    "--attach" => "Force attached owner-session behavior for `up` even if the manifest defaults to detached startup",
    "--detach" => "Force non-attached bring-up for `up` and exit once the environment reaches ready state",
    "--service <NAME>" => "Select one explicit service for `logs` or `shell` instead of the manifest `primary_service`",
    "--global" => "For `down`, `status`, or `stats`, discover running Effigy-managed environments across repos. For `cache list`, inspect the Effigy Colima profile's named-volume inventory, including stopped projects. For `volume list`, inspect Effigy-managed named volumes across available runtimes.",
    "--orphans" => "For `volume list --global`, show only ownerless volumes whose repo is gone or no longer declares them.",
    "--dormant" => "For repo-scoped `volume list`, show only superseded volumes the current repo no longer declares or mounts.",
    "--yes" => "Confirm destructive data, cache, or volume cleanup operations without an interactive prompt",
    "--project <NAME>" => "Restrict global cache inventory or cleanup to one inferred project name such as `acowtancy-dev`; implies profile-wide mode even without `--global`",
    "--profile <NAME>" => "For `container profile`, select a Colima profile instead of the configured/default `effigy` profile",
    "--disk <GiB>" => "For `container profile recreate`, set the managed Colima profile disk size for this recreate; interactive runs prompt when omitted",
    "--kind <KIND>" => "Restrict global cache inventory or cleanup to one cache kind such as `rust-target`, `node-modules`, `pnpm-store`, `cargo-registry`, or `cargo-git`; implies profile-wide mode even without `--global`",
    "--command <CMD>" => "Run one shell command string inside the selected service via `sh -lc`",
    "--follow" => "Keep streaming container logs instead of returning one bounded snapshot",
    "--keep-data" => "For `reset`, preserve generated-compose persistent named volumes and remove only ephemeral ones",
    "--db-dump <FILE>|<TARGET>|<TARGET>=<FILE>" => "Compatibility alias for positional `data dump` specs. A bare target writes `./<target>.sql`. Explicit `oci://` destinations stage a local dump and report artifact metadata.",
    "--push" => "For explicit `oci://` dump destinations, publish the captured artifact after the local dump is staged. Local-only dumps reject `--push`.",
    "--db-seed <FILE|OCI>|<TARGET>=<FILE|OCI>" => "Stage one SQL dump or explicit `oci://` artifact for `data seed`; single-database bundles can omit the target, multi-database bundles must name one, and a bare target reads `./<target>.sql`. `data seed` currently targets the repo default container only.",
    "--no-prompt" => "Suppress interactive DB-seed collection for `data seed` and bootstrap flows that would otherwise prompt on a real TTY",
];
