use super::super::{HelpRenderer, HelpResult};
use super::shared::render_standard_topic_help;

pub(crate) fn render_container_help<R: HelpRenderer>(renderer: &mut R) -> HelpResult<()> {
    render_standard_topic_help(
        renderer,
        "container",
        &[
            "Operate one manifest-defined Colima-backed container environment by name or through the manifest default alias.",
            "V1 stays explicit: host-facing ports and repo-relative mounts are declared in `[containers.*.host]`, and attached sessions shut the environment down on owner exit by default.",
            "Generated compose also supports bounded `shared = true` backing services for standalone shared databases and caches on the product-owned path.",
            "Mounted sibling repos listed in `systems.<name>.mounts` auto-adopt producer `[isolation].paths` into workspace containers, and Colima/nerdctl now preflights oversized mount payloads before compose-up.",
            "`container data seed` currently targets the repo default container only and stays on the generated-compose path, while `container data dump` exports logical SQL dumps from generated-compose database services.",
            "`container cache list` inventories purge-safe isolated build caches like Rust `target` and package-manager `node_modules` volumes without touching persistent app data, and `cache prune` removes only those disposable volumes.",
        ],
        &[
            "effigy container up [--repo <PATH>] [--attach|--detach] [--json]",
            "effigy container <NAME> up [--repo <PATH>] [--attach|--detach] [--json]",
            "effigy container down [--repo <PATH>] [--json]",
            "effigy container down --all [--json]",
            "effigy container <NAME> down [--repo <PATH>] [--json]",
            "effigy container status [--repo <PATH>] [--json]",
            "effigy container status --all [--json]",
            "effigy container stats --all [--json]",
            "effigy container <NAME> status [--repo <PATH>] [--json]",
            "effigy container cache list [--repo <PATH>] [--all] [--json]",
            "effigy container cache prune [--repo <PATH>] [--all] [--yes] [--json]",
            "effigy container <NAME> cache list [--repo <PATH>] [--json]",
            "effigy container <NAME> cache prune [--repo <PATH>] [--yes] [--json]",
            "effigy container data list [--repo <PATH>] [--json]",
            "effigy container <NAME> data list [--repo <PATH>] [--json]",
            "effigy container data export <VOLUME> <PATH> [--repo <PATH>] [--json]",
            "effigy container <NAME> data export <VOLUME> <PATH> [--repo <PATH>] [--json]",
            "effigy container [<NAME>] data dump [<FILE>|<TARGET>|<TARGET>=<FILE>]... [--db-dump <FILE>|<TARGET>|<TARGET>=<FILE>]... [--repo <PATH>] [--json]",
            "effigy container data import <VOLUME> <PATH> [--repo <PATH>] [--yes] [--json]",
            "effigy container <NAME> data import <VOLUME> <PATH> [--repo <PATH>] [--yes] [--json]",
            "effigy container data pull-production [--repo <PATH>] [--yes] [--json]",
            "effigy container <NAME> data pull-production [--repo <PATH>] [--yes] [--json]",
            "effigy container data seed [--db-seed <FILE|OCI>|<TARGET>=<FILE|OCI>]... [--no-prompt] [--yes] [--repo <PATH>] [--json]",
            "effigy container <NAME> logs [--repo <PATH>] [--service <NAME>] [--follow] [--json]",
            "effigy container <NAME> shell [--repo <PATH>] [--service <NAME>] [--command <CMD>]",
            "effigy container <NAME> reset [--repo <PATH>] [--keep-data] [--json]",
            "effigy container <NAME> eject [--repo <PATH>] [--json]",
            "effigy --json container up [--repo <PATH>]",
        ],
        &[
            ("--repo <PATH>", "Override target repository path"),
            (
                "--attach",
                "Force attached owner-session behavior for `up` even if the manifest defaults to detached startup",
            ),
            (
                "--detach",
                "Force non-attached bring-up for `up` and exit once the environment reaches ready state",
            ),
            (
                "--service <NAME>",
                "Select one explicit service for `logs` or `shell` instead of the manifest `primary_service`",
            ),
            (
                "--all",
                "For `down`, `status`, or `stats`, discover running Effigy-managed environments across repos. For `cache list`, inspect the Effigy Colima profile's named-volume inventory, including stopped projects.",
            ),
            (
                "--command <CMD>",
                "Run one shell command string inside the selected service via `sh -lc`",
            ),
            (
                "--follow",
                "Keep streaming container logs instead of returning one bounded snapshot",
            ),
            (
                "--keep-data",
                "For `reset`, preserve generated-compose persistent named volumes and remove only ephemeral ones",
            ),
            (
                "--yes",
                "Confirm destructive data or cache cleanup operations without an interactive prompt",
            ),
            (
                "--db-dump <FILE>|<TARGET>|<TARGET>=<FILE>",
                "Compatibility alias for positional `data dump` specs. A bare target writes `./<target>.sql`. Output paths are relative to the invocation cwd unless absolute.",
            ),
            (
                "--db-seed <FILE|OCI>|<TARGET>=<FILE|OCI>",
                "Stage one SQL dump or explicit `oci://` artifact for `data seed`; single-database bundles can omit the target, multi-database bundles must name one, and a bare target reads `./<target>.sql`. `data seed` currently targets the repo default container only.",
            ),
            (
                "--no-prompt",
                "Suppress interactive DB-seed collection for `data seed` and bootstrap flows that would otherwise prompt on a real TTY",
            ),
            ("--json", "Render machine-readable container payloads"),
            ("-h, --help", "Print command help"),
        ],
        &[
            "effigy container up",
            "effigy container web up --detach",
            "effigy container web status",
            "effigy container down --all",
            "effigy container status --all",
            "effigy container stats --all",
            "effigy container cache list",
            "effigy container cache list --all",
            "effigy container cache prune",
            "effigy container cache prune --all --yes",
            "effigy container web data list",
            "effigy container web data export fixture-web-dev-db-data ./backup.tar.gz",
            "effigy container data dump legacy_mysql",
            "effigy container data dump --db-dump legacy_mysql",
            "effigy container data dump --db-dump ./latest.sql",
            "effigy container data dump --db-dump app=./app.sql --db-dump app_test=./app_test.sql",
            "effigy container web data import fixture-web-dev-db-data ./backup.tar.gz",
            "effigy container web data pull-production",
            "effigy container data seed --db-seed legacy_mysql",
            "effigy container data seed --db-seed ./latest.sql",
            "effigy container data seed --db-seed app=oci://ghcr.io/acme/private-data:uat",
            "effigy container data seed --db-seed cbs=./cbs.sql --db-seed cbs-mortcalc=./mortcalc.sql",
            "effigy container web logs --follow",
            "effigy container web shell --command \"php artisan tinker\"",
            "effigy container web reset --keep-data",
            "effigy container web reset",
            "effigy container web eject",
        ],
    )
}
