use super::super::{HelpRenderer, HelpResult};
use super::shared::{render_standard_topic_help_with_common_options, CommonOption};

pub(crate) fn render_container_help<R: HelpRenderer + ?Sized>(renderer: &mut R) -> HelpResult<()> {
    render_standard_topic_help_with_common_options(
        renderer,
        "container",
        &[
            "Operate one manifest-defined local container environment by name or through the manifest default alias.",
            "V1 stays explicit: host-facing ports and repo-relative mounts are declared in `[containers.*.host]`, and attached sessions shut the environment down on owner exit by default.",
            "Generated compose also supports bounded `shared = true` backing services for standalone shared databases and caches on the product-owned path.",
            "Mounted sibling repos listed in `systems.<name>.mounts` auto-adopt producer `[isolation].paths` into workspace containers, and the Colima/containerd path now preflights oversized mount payloads before compose-up.",
            "`container data seed` currently targets the repo default container only and stays on the generated-compose path, while `container data dump` exports logical SQL dumps from generated-compose database services.",
            "`container cache list` inventories purge-safe isolated build caches like Rust `target` and package-manager `node_modules` volumes without touching persistent app data, and `cache prune` removes only those disposable volumes.",
            "`container volume list` now follows normal repo scope by default; add `--global` for cross-runtime inventory, use `--dormant` for repo-scoped superseded volumes, and use `--orphans` only with `--global` for true ownerless volumes.",
        ],
        &[
            "effigy container up [--repo <PATH>] [--attach|--detach] [--json]",
            "effigy container <NAME> up [--repo <PATH>] [--attach|--detach] [--json]",
            "effigy container down [--repo <PATH>] [--json]",
            "effigy container down --global [--json]",
            "effigy container <NAME> down [--repo <PATH>] [--json]",
            "effigy container status [--repo <PATH>] [--json]",
            "effigy container status --global [--json]",
            "effigy container stats --global [--json]",
            "effigy container <NAME> status [--repo <PATH>] [--json]",
            "effigy container volume list [--repo <PATH>] [--dormant] [--json]",
            "effigy container volume list --global [--orphans] [--json]",
            "effigy container volume prune [--repo <PATH>] --dormant [--yes] [--json]",
            "effigy container volume prune --global --orphans [--yes] [--json]",
            "effigy container cache list [--repo <PATH>] [--global] [--project <NAME>] [--kind <KIND>] [--json]",
            "effigy container cache prune [--repo <PATH>] [--global] [--project <NAME>] [--kind <KIND>] [--yes] [--json]",
            "effigy container <NAME> cache list [--repo <PATH>] [--json]",
            "effigy container <NAME> cache prune [--repo <PATH>] [--yes] [--json]",
            "effigy container data list [--repo <PATH>] [--json]",
            "effigy container <NAME> data list [--repo <PATH>] [--json]",
            "effigy container data export <VOLUME> <PATH> [--repo <PATH>] [--json]",
            "effigy container <NAME> data export <VOLUME> <PATH> [--repo <PATH>] [--json]",
            "effigy container [<NAME>] data dump [<FILE>|<TARGET>|<TARGET>=<FILE|OCI>]... [--db-dump <FILE>|<TARGET>|<TARGET>=<FILE|OCI>]... [--push] [--repo <PATH>] [--json]",
            "effigy container data import <VOLUME> <PATH> [--repo <PATH>] [--yes] [--json]",
            "effigy container <NAME> data import <VOLUME> <PATH> [--repo <PATH>] [--yes] [--json]",
            "effigy container data pull-production [--repo <PATH>] [--yes] [--json]",
            "effigy container <NAME> data pull-production [--repo <PATH>] [--yes] [--json]",
            "effigy container data seed [--db-seed <FILE|OCI>|<TARGET>=<FILE|OCI>]... [--no-prompt] [--yes] [--repo <PATH>] [--json]",
            "effigy container <NAME> logs [--repo <PATH>] [--service <NAME>] [--follow] [--json]",
            "effigy container <NAME> shell [--repo <PATH>] [--service <NAME>] [--command <CMD>]",
            "effigy container <NAME> reset [--repo <PATH>] [--keep-data] [--json]",
            "effigy container <NAME> eject [--repo <PATH>] [--json]",
            "effigy --json container up [--repo <PATH>]",
        ],
        &[CommonOption::Repo],
        &[
            (
                "--attach",
                "Force attached owner-session behavior for `up` even if the manifest defaults to detached startup",
            ),
            (
                "--detach",
                "Force non-attached bring-up for `up` and exit once the environment reaches ready state",
            ),
            (
                "--service <NAME>",
                "Select one explicit service for `logs` or `shell` instead of the manifest `primary_service`",
            ),
            (
                "--global",
                "For `down`, `status`, or `stats`, discover running Effigy-managed environments across repos. For `cache list`, inspect the Effigy Colima profile's named-volume inventory, including stopped projects. For `volume list`, inspect Effigy-managed named volumes across available runtimes.",
            ),
            (
                "--orphans",
                "For `volume list --global`, show only ownerless volumes whose repo is gone or no longer declares them.",
            ),
            (
                "--dormant",
                "For repo-scoped `volume list`, show only superseded volumes the current repo no longer declares or mounts.",
            ),
            (
                "--yes",
                "Confirm destructive data, cache, or volume cleanup operations without an interactive prompt",
            ),
            (
                "--project <NAME>",
                "Restrict global cache inventory or cleanup to one inferred project name such as `acowtancy-dev`; implies profile-wide mode even without `--global`",
            ),
            (
                "--kind <KIND>",
                "Restrict global cache inventory or cleanup to one cache kind such as `rust-target`, `node-modules`, `pnpm-store`, `cargo-registry`, or `cargo-git`; implies profile-wide mode even without `--global`",
            ),
            (
                "--command <CMD>",
                "Run one shell command string inside the selected service via `sh -lc`",
            ),
            (
                "--follow",
                "Keep streaming container logs instead of returning one bounded snapshot",
            ),
            (
                "--keep-data",
                "For `reset`, preserve generated-compose persistent named volumes and remove only ephemeral ones",
            ),
            (
                "--db-dump <FILE>|<TARGET>|<TARGET>=<FILE>",
                "Compatibility alias for positional `data dump` specs. A bare target writes `./<target>.sql`. Explicit `oci://` destinations stage a local dump and report artifact metadata.",
            ),
            (
                "--push",
                "For explicit `oci://` dump destinations, publish the captured artifact after the local dump is staged. Local-only dumps reject `--push`.",
            ),
            (
                "--db-seed <FILE|OCI>|<TARGET>=<FILE|OCI>",
                "Stage one SQL dump or explicit `oci://` artifact for `data seed`; single-database bundles can omit the target, multi-database bundles must name one, and a bare target reads `./<target>.sql`. `data seed` currently targets the repo default container only.",
            ),
            (
                "--no-prompt",
                "Suppress interactive DB-seed collection for `data seed` and bootstrap flows that would otherwise prompt on a real TTY",
            ),
        ],
        &[
            CommonOption::Json("Render machine-readable container payloads"),
            CommonOption::Help,
        ],
        &[
            "effigy container up",
            "effigy container web up --detach",
            "effigy container web status",
            "effigy container down --global",
            "effigy container status --global",
            "effigy container stats --global",
            "effigy container volume list",
            "effigy container volume list --dormant",
            "effigy container volume list --repo ~/Dev/projects/underlay-reference --dormant",
            "effigy container volume list --global",
            "effigy container volume list --global --orphans",
            "effigy container volume prune --dormant --yes",
            "effigy container volume prune --global --orphans --yes",
            "effigy container cache list",
            "effigy container cache list --global",
            "effigy container cache list --project acowtancy-dev",
            "effigy container cache list --kind rust-target",
            "effigy container cache prune",
            "effigy container cache prune --project acowtancy-dev --yes",
            "effigy container cache prune --kind rust-target --yes",
            "effigy container cache prune --global --yes",
            "effigy container web data list",
            "effigy container web data export fixture-web-dev-db-data ./backup.tar.gz",
            "effigy container data dump legacy_mysql",
            "effigy container data dump --db-dump legacy_mysql",
            "effigy container data dump --db-dump ./latest.sql",
            "effigy container data dump --db-dump app=./app.sql --db-dump app_test=./app_test.sql",
            "effigy container data dump --db-dump app=oci://ghcr.io/acme/uat-content:2026-05-07 --push --json",
            "effigy container web data import fixture-web-dev-db-data ./backup.tar.gz",
            "effigy container web data pull-production",
            "effigy container data seed --db-seed legacy_mysql",
            "effigy container data seed --db-seed ./latest.sql",
            "effigy container data seed --db-seed app=oci://ghcr.io/acme/private-data:uat",
            "effigy container data seed --db-seed cbs=./cbs.sql --db-seed cbs-mortcalc=./mortcalc.sql",
            "effigy container web logs --follow",
            "effigy container web shell --command \"php artisan tinker\"",
            "effigy container web reset --keep-data",
            "effigy container web reset",
            "effigy container web eject",
        ],
    )
}
