[containers]
default = "__CONTAINER_NAME__"

[containers.__CONTAINER_NAME__]
driver = "colima"
startup = "detached"
project_name = "__PROJECT_NAME__"
primary_service = "__WORKSPACE_SERVICE_NAME__"
working_dir = "/var/www/html"

[containers.__CONTAINER_NAME__.lifecycle]
on_task_exit = "stop"
shutdown = "graceful"

[containers.__CONTAINER_NAME__.dns]
routes = [
  { domain = "__HOST__", tls = true, service = "web" },
  { domain = "pma.__HOST__", tls = true, service = "pma" },
__ZEST_ROUTE__
]

[containers.__CONTAINER_NAME__.aliases]
php = "__WORKSPACE_SERVICE_NAME__"
composer = { service = "__WORKSPACE_SERVICE_NAME__", command = "composer" }
mysql = { service = "db", command = "mysql -uroot{% if services.db.params.password %} -p{{ services.db.params.password }}{% endif %} {{ services.db.params.database }}" }

[containers.__CONTAINER_NAME__.services.__WORKSPACE_SERVICE_NAME__]
catalog = "php-fpm"
version = "8.4"
document_root = "."
isolated_dirs = ["vendor", "node_modules"]
host_ports = [
__ZEST_HOST_PORTS__
]
mount_host_ssh_dir = true
node_version = "20"
node_global_packages = ["eclint"]
composer_global_packages = ["decodelabs/effigy"]
extensions = [
__PHP_EXTENSIONS__
]

[containers.__CONTAINER_NAME__.services.web]
catalog = "nginx"
variant = "decodelabs"
document_root = "."

[containers.__CONTAINER_NAME__.services.db]
catalog = "mariadb"
version = "10.11"
database = "__DATABASE__"
databases = __DATABASES__

[containers.__CONTAINER_NAME__.services.pma]
catalog = "phpmyadmin"
version = "latest"
database_host = "db"

[containers.__CONTAINER_NAME__.services.memcache]
catalog = "memcached"
memory = 128

[containers.__CONTAINER_NAME__.services.redis]
catalog = "redis"
version = "7"

[systems]
default = "__SYSTEM_NAME__"

[systems.__SYSTEM_NAME__]
default_workspace = "__DEFAULT_WORKSPACE__"

[systems.__SYSTEM_NAME__.workspaces.__DEFAULT_WORKSPACE__]
container = "__CONTAINER_NAME__"

[tasks.dev]
workspace = "__DEFAULT_WORKSPACE__"

[tasks.seed]
workspace = "__DEFAULT_WORKSPACE__"
stay_in_shell = true
run_in = "container"
run = [{ rhai = "{{ bundle.root }}/scripts/seed-latest-db-dump.rhai" }]

[tasks.release]
run = "\"${COMPOSER_HOME:-$HOME/.config/composer}/vendor/bin/effigy\" release"

[defer]
run = "\"${COMPOSER_HOME:-$HOME/.config/composer}/vendor/bin/effigy\" {request} {args}"
run_in = "container"
