#!/bin/bash
# Behavioral harness for the effigy-entrypoint generated by the bundled
# workspace-rust-bun catalog Dockerfile (papercut 2f1b0df3).
#
# What it exercises: the real generation block. It extracts the
# `RUN set -eux; \` block that writes /usr/local/bin/effigy-entrypoint from
# the Dockerfile, runs it unchanged (retargeted into the fixture), and then
# executes the produced script. No image build, no docker, no duplicate
# implementation — every behavioral byte is the generated entrypoint.
#
# Sandboxing: the generated script hardcodes host paths (/run/host-services,
# /tmp, /var/log, /usr/local/share/ca-certificates). The harness rewrites
# exactly those four assignment lines into a fresh mktemp fixture and
# injects a fake socat / update-ca-certificates through PATH. Any other
# change to the generated shape fails the harness loudly.
#
# Cases:
#   C  writable log, no host socket      — root-mode diagnostics stay honest
#   D  host socket + mkcert CA + bridge  — root bridge/trust branch intent
#   E  update-ca-certificates fails      — trust failure reported, start lives
#   F  argv/exit preservation            — exec "$@" passes argv and status
#   A  non-root, log dir unwritable      — the papercut: start must survive
#   B  non-root, existing log unwritable — same, log left by an earlier root run
#
# While the bundled baseline predates the catalog-pack fix, cases A and B
# reproduce the papercut (the entrypoint exits on its unguarded log writes
# before exec). The harness reports them as SKIP with the papercut id
# instead of failing, and says so in its summary. Once a fixed pack version
# is imported as the baseline, they assert the full fixed contract:
#   - startup reaches the requested command with argv and exit preserved
#   - unavailable optional forwarding is reported on stderr (the log is
#     unwritable, so stderr is the only visible channel)
#   - nothing claims the bridge came up when it did not
#
# Reuse: pass a Dockerfile path as $1 to exercise another copy of the same
# generated entrypoint (e.g. the effigy-catalog-pack checkout's
# pack/workspace-rust-bun/Dockerfile) before it is published and imported.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOCKERFILE="${1:-$REPO_ROOT/crates/effigy-catalog/catalog/workspace-rust-bun/Dockerfile}"
PAPERCUT_ID="2f1b0df3-a0d4-45ab-98ef-7086b37295f8"

failures=0
skips=0
passes=0

note() { printf '%s\n' "$*"; }
pass() { note "PASS: $*"; passes=$((passes + 1)); }
fail() { note "FAIL: $*"; failures=$((failures + 1)); }
skip_case() { note "SKIP: $*"; skips=$((skips + 1)); }

command -v python3 >/dev/null 2>&1 || {
  note "FAIL: python3 is required to create fixture UNIX sockets"
  exit 1
}
[ -f "$DOCKERFILE" ] || { note "FAIL: Dockerfile not found: $DOCKERFILE"; exit 1; }

FIXTURE="$(mktemp -d)"
trap 'rm -rf "$FIXTURE"' EXIT

note "Harness fixture: $FIXTURE"
note "Exercising generated entrypoint from: $DOCKERFILE"
note ""

# ── Generate the entrypoint from the actual Dockerfile block ──────────

section_line="$(grep -n 'SSH agent socket bridge' "$DOCKERFILE" | head -1 | cut -d: -f1)"
[ -n "$section_line" ] || {
  note "FAIL: no 'SSH agent socket bridge' section in $DOCKERFILE"
  exit 1
}
run_line="$(
  tail -n +"$section_line" "$DOCKERFILE" |
    grep -n '^RUN set -eux; \\' | head -1 | cut -d: -f1
)"
chmod_line="$(
  tail -n +"$section_line" "$DOCKERFILE" |
    grep -n 'chmod 0755 /usr/local/bin/effigy-entrypoint$' | head -1 | cut -d: -f1
)"
[ -n "$run_line" ] && [ -n "$chmod_line" ] || {
  note "FAIL: could not locate the effigy-entrypoint generation block in $DOCKERFILE"
  exit 1
}
abs_run=$((section_line + run_line - 1))
abs_chmod=$((section_line + chmod_line - 1))

mkdir -p "$FIXTURE/bin"
GEN="$FIXTURE/bin/effigy-entrypoint"

# Drop the `RUN set -eux; \` wrapper line and retarget the output path into
# the fixture. The echo lines that generate the script are untouched, so the
# produced bytes are exactly what the image build produces.
sed -n "${abs_run},${abs_chmod}p" "$DOCKERFILE" |
  tail -n +2 |
  sed "s|/usr/local/bin/effigy-entrypoint|$GEN|g" >"$FIXTURE/generate.sh"
bash "$FIXTURE/generate.sh"

[ -f "$GEN" ] || { note "FAIL: generation block produced no entrypoint"; exit 1; }

# The sandbox below rewrites these exact lines; fail loudly if the generated
# shape ever drifts.
require_line() {
  grep -Fxq "$1" "$GEN" || {
    note "FAIL: generated entrypoint is missing the expected line: $1"
    exit 1
  }
}
require_line 'host_sock=/run/host-services/ssh-auth.sock'
require_line 'bridge_sock=/tmp/effigy-ssh-auth.sock'
require_line 'log=/var/log/effigy-ssh-bridge.log'
require_line 'mkcert_ca=/usr/local/share/ca-certificates/effigy-mkcert.crt'
require_line 'exec "$@"'

# ── Fixture plumbing ──────────────────────────────────────────────────

FAKEBIN="$FIXTURE/fakebin"
mkdir -p "$FAKEBIN"

cat >"$FAKEBIN/update-ca-certificates" <<'EOF'
#!/bin/bash
echo "fake update-ca-certificates invoked" >>"${FAKE_UPDATE_CA_LOG:?FAKE_UPDATE_CA_LOG required}"
if [ "${FAKE_UPDATE_CA_EXIT:-0}" != "0" ]; then
  echo "fake update-ca-certificates failing on request" >&2
  exit "${FAKE_UPDATE_CA_EXIT}"
fi
echo "fake update-ca-certificates succeeded"
EOF
chmod 0755 "$FAKEBIN/update-ca-certificates"

cat >"$FAKEBIN/socat" <<'EOF'
#!/bin/bash
# Stand-in for socat: records its argv, then binds the UNIX-LISTEN address
# so the entrypoint's `[ -S "$bridge_sock" ]` wait loop observes a socket,
# as a real listening bridge would. It does not proxy traffic; bridge
# creation is the only behavior under test.
for arg in "$@"; do
  case "$arg" in
    UNIX-LISTEN:*)
      # The address argument is UNIX-LISTEN:<path>,<options>; bind the path.
      listen_path="${arg#UNIX-LISTEN:}"
      listen_path="${listen_path%%,*}"
      python3 - "$listen_path" <<'PY'
import os, socket, sys
path = sys.argv[1]
if os.path.exists(path):
    os.unlink(path)
socket.socket(socket.AF_UNIX, socket.SOCK_STREAM).bind(path)
PY
      ;;
  esac
done
printf '%s\n' "$*" >>"${FAKE_SOCAT_LOG:?FAKE_SOCAT_LOG required}"
EOF
chmod 0755 "$FAKEBIN/socat"

cat >"$FIXTURE/probe.sh" <<'EOF'
# Requested-command stand-in: records its argv (everything after the marker
# path) and exits with ${PROBE_EXIT:-0}.
marker="$1"
shift
printf '%s\n' "$*" >"$marker"
exit "${PROBE_EXIT:-0}"
EOF
chmod 0755 "$FIXTURE/probe.sh"

make_socket() {
  python3 - "$1" <<'PY'
import os, socket, sys
path = sys.argv[1]
os.makedirs(os.path.dirname(path), exist_ok=True)
if os.path.exists(path):
    os.unlink(path)
socket.socket(socket.AF_UNIX, socket.SOCK_STREAM).bind(path)
PY
}

# Rewrite exactly the four hardcoded path assignments into the fixture.
sandbox_entrypoint() {
  local dest="$1"
  sed \
    -e "s|^host_sock=.*|host_sock='$host_sock'|" \
    -e "s|^bridge_sock=.*|bridge_sock='$bridge_sock'|" \
    -e "s|^log=.*|log='$log_path'|" \
    -e "s|^mkcert_ca=.*|mkcert_ca='$mkcert_ca'|" \
    "$GEN" >"$dest"
  grep -Fxq "host_sock='$host_sock'" "$dest" ||
    { note "FAIL: sandboxing lost host_sock= in $dest"; exit 1; }
  grep -Fxq "bridge_sock='$bridge_sock'" "$dest" ||
    { note "FAIL: sandboxing lost bridge_sock= in $dest"; exit 1; }
  grep -Fxq "log='$log_path'" "$dest" ||
    { note "FAIL: sandboxing lost log= in $dest"; exit 1; }
  grep -Fxq "mkcert_ca='$mkcert_ca'" "$dest" ||
    { note "FAIL: sandboxing lost mkcert_ca= in $dest"; exit 1; }
}

entry_exit=0
case_dir=""
host_sock=""
bridge_sock=""
log_path=""
mkcert_ca=""

setup_case() {
  case_dir="$FIXTURE/case-$1"
  rm -rf "$case_dir"
  mkdir -p "$case_dir/run/host-services" "$case_dir/tmp" "$case_dir/state" "$case_dir/ca"
  host_sock="$case_dir/run/host-services/ssh-auth.sock"
  bridge_sock="$case_dir/tmp/effigy-ssh-auth.sock"
  log_path="$case_dir/state/effigy-ssh-bridge.log"
  mkcert_ca="$case_dir/ca/effigy-mkcert.crt"
  sandbox_entrypoint "$case_dir/entrypoint"
  : >"$case_dir/fake-update-ca.log"
  : >"$case_dir/fake-socat.log"
  : >"$case_dir/stdout.txt"
  : >"$case_dir/stderr.txt"
  rm -f "$case_dir/marker.txt"
}

exec_case() {
  entry_exit=0
  (
    cd "$case_dir" &&
      PATH="$FAKEBIN:$PATH" \
        FAKE_UPDATE_CA_LOG="$case_dir/fake-update-ca.log" \
        FAKE_SOCAT_LOG="$case_dir/fake-socat.log" \
        FAKE_UPDATE_CA_EXIT="${FAKE_UPDATE_CA_EXIT:-0}" \
        PROBE_EXIT="${PROBE_EXIT:-0}" \
        bash ./entrypoint \
        bash "$FIXTURE/probe.sh" "$case_dir/marker.txt" --alpha 'beta two' gamma \
        >"$case_dir/stdout.txt" 2>"$case_dir/stderr.txt"
  ) || entry_exit=$?
}

command_ran() { [ -f "$case_dir/marker.txt" ] && [ "$entry_exit" -eq "${PROBE_EXIT:-0}" ]; }

# Shared contract for the non-root, unwritable-log cases.
assert_nonroot_survival() {
  local name="$1"
  if [ ! -f "$case_dir/marker.txt" ] && [ "$entry_exit" -ne "${PROBE_EXIT:-0}" ]; then
    if grep -Fq "$log_path" "$case_dir/stderr.txt"; then
      skip_case "$name: bundled baseline still exits on the unwritable bridge log before exec (papercut $PAPERCUT_ID; fix ships through effigy-catalog-pack and is imported as a new baseline)"
    else
      fail "$name: entrypoint exited $entry_exit before running the requested command, and stderr does not name the log path"
    fi
    return 1
  fi
  [ -f "$case_dir/marker.txt" ] ||
    { fail "$name: requested command never ran (no argv marker)"; return 1; }
  [ "$entry_exit" -eq "${PROBE_EXIT:-0}" ] ||
    { fail "$name: expected exit ${PROBE_EXIT:-0}, got $entry_exit"; return 1; }
  grep -Fq 'WARNING host_sock missing' "$case_dir/stderr.txt" ||
    { fail "$name: missing-socket warning not reported on stderr while the log is unwritable"; return 1; }
  if grep -Fq 'bridge_sock created' "$case_dir/stderr.txt" "$case_dir/stdout.txt"; then
    fail "$name: claims the bridge socket was created without any host socket"
    return 1
  fi
  return 0
}

# ── Case C: writable log, no host socket ──────────────────────────────
setup_case C
exec_case
if command_ran; then
  pass "C: reaches the requested command with a writable bridge log"
else
  fail "C: expected the requested command to run, got exit $entry_exit"
fi
if [ -s "$log_path" ]; then
  pass "C: writes start diagnostics to the log"
else
  fail "C: log is empty though it is writable"
fi
if grep -Eq 'dev uid=[0-9]+ gid=[0-9]+' "$log_path"; then
  pass "C: records the dev uid/gid"
else
  fail "C: dev uid/gid line missing from the log"
fi
if grep -Fq 'WARNING host_sock missing' "$log_path"; then
  pass "C: reports the missing host socket in the log"
else
  fail "C: missing host socket not reported in the log"
fi
if grep -Fq 'bridge_sock created' "$log_path"; then
  fail "C: claims a bridge socket without any host socket"
else
  pass "C: makes no bridge claim when no host socket exists"
fi

# ── Case D: host socket + mkcert CA + successful bridge ───────────────
setup_case D
make_socket "$host_sock"
printf '%s\n' '-----BEGIN FAKE ROOT CA-----' >"$mkcert_ca"
exec_case
if command_ran; then
  pass "D: reaches the requested command with host forwarding present"
else
  fail "D: expected the requested command to run, got exit $entry_exit"
fi
if grep -Fq 'host_sock present at' "$log_path"; then
  pass "D: records the host socket"
else
  fail "D: host socket not recorded in the log"
fi
if grep -Fq 'socat pid=' "$log_path"; then
  pass "D: starts the bridge and records its pid"
else
  fail "D: bridge start not recorded in the log"
fi
if grep -Fq 'bridge_sock created at' "$log_path"; then
  pass "D: records the created bridge socket"
else
  fail "D: bridge socket creation not recorded in the log"
fi
if [ -S "$bridge_sock" ]; then
  pass "D: bridge socket exists as a socket"
else
  fail "D: bridge socket is not a socket"
fi
if grep -Eq 'user=[0-9]+,group=[0-9]+,mode=0600' "$case_dir/fake-socat.log"; then
  pass "D: bridge is created dev-owned with mode 0600"
else
  fail "D: bridge socat invocation lacks user/group/mode=0600 policy"
fi
if grep -Fq 'mkcert root CA installed into system trust store' "$log_path"; then
  pass "D: records the mkcert CA install"
else
  fail "D: mkcert CA install not recorded in the log"
fi
if [ -s "$case_dir/fake-update-ca.log" ]; then
  pass "D: invokes update-ca-certificates when a CA is present"
else
  fail "D: update-ca-certificates never invoked despite a present CA"
fi

# ── Case E: update-ca-certificates fails ──────────────────────────────
setup_case E
make_socket "$host_sock"
printf '%s\n' '-----BEGIN FAKE ROOT CA-----' >"$mkcert_ca"
FAKE_UPDATE_CA_EXIT=1
exec_case
FAKE_UPDATE_CA_EXIT=0
if command_ran; then
  pass "E: still reaches the requested command when trust setup fails"
else
  fail "E: trust setup failure killed startup, exit $entry_exit"
fi
if grep -Fq 'WARNING update-ca-certificates failed' "$log_path"; then
  pass "E: reports the trust setup failure honestly"
else
  fail "E: trust setup failure not reported in the log"
fi
if grep -Fq 'mkcert root CA installed into system trust store' "$log_path"; then
  fail "E: claims the CA was installed although update failed"
else
  pass "E: makes no false CA claim"
fi

# ── Case F: argv/exit preservation ────────────────────────────────────
setup_case F
PROBE_EXIT=7
exec_case
PROBE_EXIT=0
if [ "$entry_exit" -eq 7 ]; then
  pass "F: propagates the requested command's exit status (7)"
else
  fail "F: expected exit 7, got $entry_exit"
fi
expected_argv="--alpha beta two gamma"
actual_argv="$(cat "$case_dir/marker.txt" 2>/dev/null || true)"
if [ "$actual_argv" = "$expected_argv" ]; then
  pass "F: passes the requested command argv through exec unchanged"
else
  fail "F: argv not preserved: ${actual_argv:-<missing>}"
fi

# ── Cases A/B: non-root start with an unwritable bridge log ───────────
# The harness already runs as a non-root host user (no root required); the
# unwritable location stands in for the root-owned /var/log path.
setup_case A
chmod 555 "$case_dir/state"
exec_case
if assert_nonroot_survival "A (log directory unwritable)"; then
  if [ -e "$log_path" ]; then
    fail "A: log file was created inside an unwritable directory"
  else
    pass "A: non-root start survives an unwritable log directory"
  fi
fi

setup_case B
: >"$log_path"
chmod 444 "$log_path"
exec_case
if assert_nonroot_survival "B (existing log unwritable)"; then
  pass "B: non-root start survives an unwritable existing log"
fi

# ── Summary ───────────────────────────────────────────────────────────
note ""
note "Summary: $passes passed, $skips skipped, $failures failed"
if [ "$skips" -gt 0 ]; then
  note "Skips are the papercut $PAPERCUT_ID family: the bundled baseline entrypoint"
  note "still exits on its unguarded bridge-log writes as non-root. The fix is"
  note "canonical in inflatable-cookie/effigy-catalog-pack; after it is published"
  note "and imported as the baseline, these cases assert the full fixed contract."
fi
[ "$failures" -eq 0 ] || exit 1
exit 0
