#!/bin/bash
# Behavioral harness for the effigy-entrypoint generated by the bundled
# workspace-rust-bun and php-fpm catalog Dockerfiles (papercut
# 2f1b0df3-a0d4-45ab-98ef-7086b37295f8, fixed in catalog-pack v1.1.1).
#
# What it exercises: the real generation block. For each Dockerfile it
# extracts the `RUN set -eux; \` block that writes
# /usr/local/bin/effigy-entrypoint, runs it unchanged (retargeted into the
# fixture), and then executes the produced script. No image build, no
# docker, no duplicate implementation — every behavioral byte is the
# generated entrypoint.
#
# Sandboxing: the generated scripts hardcode host paths (/run/host-services,
# /tmp, /var/log, /usr/local/share/ca-certificates). The harness rewrites
# exactly those four assignment lines into a fresh mktemp fixture and
# injects fake socat / update-ca-certificates / id through PATH. Any other
# change to the generated shape fails the harness loudly.
#
# Identity: every unsimulated case runs as the real non-root host user —
# the permissions evidence the brief requires. The root-only bridge/trust
# diagnostics are covered by simulating uid 0 through the fake `id`; the
# root branch makes no privileged host calls (its socat/update-ca work is
# fixture-injected). php-fpm's root-only PHP secrets/msmtp initialization
# touches container-only paths (/run/effigy, /usr/local/share/effigy) and is
# exercised by the pack repository's own entrypoint check
# (scripts/catalog_pack_entrypoint_check.py), so it is out of this matrix.
#
# Cases per catalog:
#   A  non-root, log dir unwritable, no host socket — start survives; the
#      unavailable log and missing forwarding are reported on stderr
#   B  non-root, existing log unwritable — same, log left by an earlier run
#   C  non-root, writable log, no host socket — diagnostics land in the log
#      and nothing leaks to stderr
#   D  simulated root, host socket + mkcert CA — root bridge/trust branch:
#      dev-owned mode=0600 bridge, CA installed via update-ca-certificates
#   E  simulated root, update-ca-certificates fails — trust failure reported,
#      start lives, no false CA claim
#   G  non-root, host socket + mkcert CA — honest refusal to touch system
#      trust as non-root, bridge still comes up via the umask branch
#   F  non-root, argv/exit preservation — exec "$@" passes argv and status
#
# A skip means a generated entrypoint exited on the unwritable bridge log
# before exec — the papercut signature. The bundled baseline has been fixed
# since catalog-pack v1.1.1, so any skip is a regression and fails the run.
#
# Reuse: pass Dockerfile paths as arguments to exercise other copies of the
# same generated entrypoint (defaults: the two bundled snapshots).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOCKERFILES=()
if [ "$#" -gt 0 ]; then
  DOCKERFILES=("$@")
else
  DOCKERFILES=(
    "$REPO_ROOT/crates/effigy-catalog/catalog/workspace-rust-bun/Dockerfile"
    "$REPO_ROOT/crates/effigy-catalog/catalog/php-fpm/Dockerfile"
  )
fi
PAPERCUT_ID="2f1b0df3-a0d4-45ab-98ef-7086b37295f8"

failures=0
passes=0

note() { printf '%s\n' "$*"; }
pass() { note "PASS: $*"; passes=$((passes + 1)); }
fail() { note "FAIL: $*"; failures=$((failures + 1)); }

command -v python3 >/dev/null 2>&1 || {
  note "FAIL: python3 is required to create fixture UNIX sockets"
  exit 1
}

FIXTURE="$(mktemp -d)"
trap 'rm -rf "$FIXTURE"' EXIT

note "Harness fixture: $FIXTURE"
for df in "${DOCKERFILES[@]}"; do
  [ -f "$df" ] || { note "FAIL: Dockerfile not found: $df"; exit 1; }
done
note ""

# ── Shared fixture plumbing ───────────────────────────────────────────

FAKEBIN="$FIXTURE/fakebin"
mkdir -p "$FAKEBIN"

cat >"$FAKEBIN/update-ca-certificates" <<'EOF'
#!/bin/bash
echo "fake update-ca-certificates invoked" >>"${FAKE_UPDATE_CA_LOG:?FAKE_UPDATE_CA_LOG required}"
if [ "${FAKE_UPDATE_CA_EXIT:-0}" != "0" ]; then
  echo "fake update-ca-certificates failing on request" >&2
  exit "${FAKE_UPDATE_CA_EXIT}"
fi
echo "fake update-ca-certificates succeeded"
EOF
chmod 0755 "$FAKEBIN/update-ca-certificates"

cat >"$FAKEBIN/socat" <<'EOF'
#!/bin/bash
# Stand-in for socat: records its argv, then binds the UNIX-LISTEN address
# so the entrypoint's `[ -S "$bridge_sock" ]` wait loop observes a socket,
# as a real listening bridge would. It does not proxy traffic; bridge
# creation is the only behavior under test.
for arg in "$@"; do
  case "$arg" in
    UNIX-LISTEN:*)
      # The address argument is UNIX-LISTEN:<path>,<options>; bind the path.
      listen_path="${arg#UNIX-LISTEN:}"
      listen_path="${listen_path%%,*}"
      python3 - "$listen_path" <<'PY'
import os, socket, sys
path = sys.argv[1]
if os.path.exists(path):
    os.unlink(path)
socket.socket(socket.AF_UNIX, socket.SOCK_STREAM).bind(path)
PY
      ;;
  esac
done
printf '%s\n' "$*" >>"${FAKE_SOCAT_LOG:?FAKE_SOCAT_LOG required}"
EOF
chmod 0755 "$FAKEBIN/socat"

cat >"$FAKEBIN/id" <<'EOF'
#!/bin/bash
# Stand-in for id: when FAKE_ID_UID is set, `id -u` reports that uid (root
# simulation for the root-only diagnostic branch); otherwise it delegates to
# the real id.
if [ -n "${FAKE_ID_UID:-}" ]; then
  if [ "$#" -eq 1 ] && [ "$1" = "-u" ]; then
    printf '%s\n' "$FAKE_ID_UID"
    exit 0
  fi
  if [ "$#" -eq 2 ] && [ "$1" = "-u" ] && [ "$2" = "dev" ]; then
    echo "id: no such user 'dev'" >&2
    exit 1
  fi
fi
exec /usr/bin/id "$@"
EOF
chmod 0755 "$FAKEBIN/id"

cat >"$FIXTURE/probe.sh" <<'EOF'
# Requested-command stand-in: records its argv (everything after the marker
# path) and exits with ${PROBE_EXIT:-0}.
marker="$1"
shift
printf '%s\n' "$*" >"$marker"
exit "${PROBE_EXIT:-0}"
EOF
chmod 0755 "$FIXTURE/probe.sh"

make_socket() {
  python3 - "$1" <<'PY'
import os, socket, sys
path = sys.argv[1]
os.makedirs(os.path.dirname(path), exist_ok=True)
if os.path.exists(path):
    os.unlink(path)
socket.socket(socket.AF_UNIX, socket.SOCK_STREAM).bind(path)
PY
}

# ── Per-catalog suite state ───────────────────────────────────────────

GEN=""
case_dir=""
host_sock=""
bridge_sock=""
log_path=""
mkcert_ca=""
entry_exit=0
label=""

# Generate the entrypoint from the actual Dockerfile block. The sandbox
# below rewrites these exact lines; fail loudly if the shape ever drifts.
generate_entrypoint() {
  local dockerfile="$1"
  local section_line run_line chmod_line abs_run abs_chmod
  section_line="$(grep -n 'SSH agent socket bridge' "$dockerfile" | head -1 | cut -d: -f1)"
  [ -n "$section_line" ] || { note "FAIL: no 'SSH agent socket bridge' section in $dockerfile"; exit 1; }
  run_line="$(tail -n +"$section_line" "$dockerfile" | grep -n '^RUN set -eux; \\' | head -1 | cut -d: -f1)"
  chmod_line="$(tail -n +"$section_line" "$dockerfile" | grep -n 'chmod 0755 /usr/local/bin/effigy-entrypoint$' | head -1 | cut -d: -f1)"
  [ -n "$run_line" ] && [ -n "$chmod_line" ] || {
    note "FAIL: could not locate the effigy-entrypoint generation block in $dockerfile"
    exit 1
  }
  abs_run=$((section_line + run_line - 1))
  abs_chmod=$((section_line + chmod_line - 1))

  label="$(basename "$(dirname "$dockerfile")")"
  GEN="$FIXTURE/generated-$label"
  mkdir -p "$GEN.bin"

  # Drop the `RUN set -eux; \` wrapper line and retarget the output path
  # into the fixture. The echo lines that generate the script are untouched,
  # so the produced bytes are exactly what the image build produces.
  sed -n "${abs_run},${abs_chmod}p" "$dockerfile" |
    tail -n +2 |
    sed "s|/usr/local/bin/effigy-entrypoint|$GEN|g" >"$FIXTURE/generate-$label.sh"
  bash "$FIXTURE/generate-$label.sh"
  [ -f "$GEN" ] || { note "FAIL: generation block produced no entrypoint for $label"; exit 1; }

  local expected
  for expected in \
    'host_sock=/run/host-services/ssh-auth.sock' \
    'bridge_sock=/tmp/effigy-ssh-auth.sock' \
    'log=/var/log/effigy-ssh-bridge.log' \
    'mkcert_ca=/usr/local/share/ca-certificates/effigy-mkcert.crt' \
    'exec "$@"'; do
    grep -Fxq "$expected" "$GEN" || {
      note "FAIL: $label entrypoint is missing the expected line: $expected"
      exit 1
    }
  done
}

# Rewrite exactly the four hardcoded path assignments into the fixture.
sandbox_entrypoint() {
  local dest="$1"
  sed \
    -e "s|^host_sock=.*|host_sock='$host_sock'|" \
    -e "s|^bridge_sock=.*|bridge_sock='$bridge_sock'|" \
    -e "s|^log=.*|log='$log_path'|" \
    -e "s|^mkcert_ca=.*|mkcert_ca='$mkcert_ca'|" \
    "$GEN" >"$dest"
  grep -Fxq "host_sock='$host_sock'" "$dest" ||
    { note "FAIL: sandboxing lost host_sock= in $dest"; exit 1; }
  grep -Fxq "bridge_sock='$bridge_sock'" "$dest" ||
    { note "FAIL: sandboxing lost bridge_sock= in $dest"; exit 1; }
  grep -Fxq "log='$log_path'" "$dest" ||
    { note "FAIL: sandboxing lost log= in $dest"; exit 1; }
  grep -Fxq "mkcert_ca='$mkcert_ca'" "$dest" ||
    { note "FAIL: sandboxing lost mkcert_ca= in $dest"; exit 1; }
}

setup_case() {
  case_dir="$FIXTURE/case-$label-$1"
  rm -rf "$case_dir"
  mkdir -p "$case_dir/state"
  # Short socket names keep paths under the macOS AF_UNIX length limit.
  host_sock="$case_dir/hs"
  bridge_sock="$case_dir/bs"
  log_path="$case_dir/state/bridge.log"
  mkcert_ca="$case_dir/ca.crt"
  sandbox_entrypoint "$case_dir/entrypoint"
  : >"$case_dir/fake-update-ca.log"
  : >"$case_dir/fake-socat.log"
  : >"$case_dir/stdout.txt"
  : >"$case_dir/stderr.txt"
  rm -f "$case_dir/marker.txt"
}

exec_case() {
  entry_exit=0
  (
    cd "$case_dir" &&
      PATH="$FAKEBIN:$PATH" \
        FAKE_ID_UID="${FAKE_ID_UID:-}" \
        FAKE_UPDATE_CA_LOG="$case_dir/fake-update-ca.log" \
        FAKE_SOCAT_LOG="$case_dir/fake-socat.log" \
        FAKE_UPDATE_CA_EXIT="${FAKE_UPDATE_CA_EXIT:-0}" \
        PROBE_EXIT="${PROBE_EXIT:-0}" \
        bash ./entrypoint \
        bash "$FIXTURE/probe.sh" "$case_dir/marker.txt" --alpha 'beta two' gamma \
        >"$case_dir/stdout.txt" 2>"$case_dir/stderr.txt"
  ) || entry_exit=$?
}

command_ran() { [ -f "$case_dir/marker.txt" ] && [ "$entry_exit" -eq "${PROBE_EXIT:-0}" ]; }

# The papercut signature: exit before exec because of the unwritable log.
assert_no_papercut_signature() {
  local name="$1"
  if [ ! -f "$case_dir/marker.txt" ] && [ "$entry_exit" -ne "${PROBE_EXIT:-0}" ] &&
    grep -Fq "$log_path" "$case_dir/stderr.txt"; then
    fail "$name: papercut $PAPERCUT_ID regression — entrypoint exited before exec on the unwritable bridge log"
    return 1
  fi
  return 0
}

# Shared contract for the non-root, unwritable-log cases.
assert_nonroot_survival() {
  local name="$1"
  assert_no_papercut_signature "$name" || return 1
  [ -f "$case_dir/marker.txt" ] ||
    { fail "$name: requested command never ran (no argv marker)"; return 1; }
  [ "$entry_exit" -eq "${PROBE_EXIT:-0}" ] ||
    { fail "$name: expected exit ${PROBE_EXIT:-0}, got $entry_exit"; return 1; }
  grep -Fq 'WARNING bridge log unavailable' "$case_dir/stderr.txt" ||
    { fail "$name: unusable bridge log not reported on stderr"; return 1; }
  grep -Fq 'WARNING host_sock missing' "$case_dir/stderr.txt" ||
    { fail "$name: missing-socket warning not reported on stderr while the log is unwritable"; return 1; }
  if grep -Fq 'bridge_sock created' "$case_dir/stderr.txt" "$case_dir/stdout.txt"; then
    fail "$name: claims the bridge socket was created without any host socket"
    return 1
  fi
  return 0
}

run_common_cases() {
  # ── Case A: non-root, unwritable log directory, no host socket ──────
  setup_case A
  chmod 555 "$case_dir/state"
  exec_case
  if assert_nonroot_survival "[$label] A (log directory unwritable)"; then
    if [ -e "$log_path" ]; then
      fail "[$label] A: log file was created inside an unwritable directory"
    else
      pass "[$label] A: non-root start survives an unwritable log directory"
    fi
  fi

  # ── Case B: non-root, existing log unwritable ────────────────────────
  setup_case B
  : >"$log_path"
  chmod 444 "$log_path"
  exec_case
  if assert_nonroot_survival "[$label] B (existing log unwritable)"; then
    if [ -s "$log_path" ]; then
      fail "[$label] B: the unwritable log was modified"
    else
      pass "[$label] B: non-root start survives an unwritable existing log"
    fi
  fi

  # ── Case C: non-root, writable log, no host socket ───────────────────
  setup_case C
  exec_case
  if command_ran; then
    pass "[$label] C: reaches the requested command with a writable bridge log"
  else
    fail "[$label] C: expected the requested command to run, got exit $entry_exit"
  fi
  if [ -s "$log_path" ]; then
    pass "[$label] C: writes start diagnostics to the log"
  else
    fail "[$label] C: log is empty though it is writable"
  fi
  if grep -Eq 'dev uid=[0-9]+ gid=[0-9]+' "$log_path"; then
    pass "[$label] C: records the dev uid/gid"
  else
    fail "[$label] C: dev uid/gid line missing from the log"
  fi
  if grep -Fq 'WARNING host_sock missing' "$log_path"; then
    pass "[$label] C: reports the missing host socket in the log"
  else
    fail "[$label] C: missing host socket not reported in the log"
  fi
  if grep -Fq 'bridge_sock created' "$log_path"; then
    fail "[$label] C: claims a bridge socket without any host socket"
  else
    pass "[$label] C: makes no bridge claim when no host socket exists"
  fi
  if [ -s "$case_dir/stderr.txt" ]; then
    fail "[$label] C: leaked diagnostics to stderr although the log is writable"
  else
    pass "[$label] C: keeps stderr clean when the log is usable"
  fi

  # ── Case G: non-root, host socket + mkcert CA present ────────────────
  setup_case G
  make_socket "$host_sock"
  printf '%s\n' '-----BEGIN FAKE ROOT CA-----' >"$mkcert_ca"
  exec_case
  if command_ran; then
    pass "[$label] G: reaches the requested command with host forwarding present as non-root"
  else
    fail "[$label] G: expected the requested command to run, got exit $entry_exit"
  fi
  if grep -Fq 'WARNING non-root startup cannot install the mkcert root CA' "$log_path"; then
    pass "[$label] G: honestly reports that non-root startup cannot install the CA"
  else
    fail "[$label] G: missing the honest non-root CA refusal"
  fi
  if [ -s "$case_dir/fake-update-ca.log" ]; then
    fail "[$label] G: invoked update-ca-certificates as non-root although it cannot succeed"
  else
    pass "[$label] G: does not attempt the system trust update as non-root"
  fi
  if grep -Fq 'host_sock present at' "$log_path"; then
    pass "[$label] G: records the host socket"
  else
    fail "[$label] G: host socket not recorded in the log"
  fi
  if grep -Fq 'socat pid=' "$log_path"; then
    pass "[$label] G: starts the bridge and records its pid"
  else
    fail "[$label] G: bridge start not recorded in the log"
  fi
  if [ -S "$bridge_sock" ]; then
    pass "[$label] G: bridge socket exists as a socket"
  else
    fail "[$label] G: bridge socket is not a socket"
  fi
  if grep -Fq 'mode=0600' "$case_dir/fake-socat.log"; then
    pass "[$label] G: bridge socket enforces mode 0600"
  else
    fail "[$label] G: bridge socat invocation lacks mode=0600"
  fi
  if grep -Eq 'user=[0-9]+,group=[0-9]+' "$case_dir/fake-socat.log"; then
    fail "[$label] G: non-root bridge tries chown-style user/group options"
  else
    pass "[$label] G: non-root bridge uses the umask branch, not user=/group="
  fi

  # ── Case F: non-root, argv/exit preservation ─────────────────────────
  setup_case F
  PROBE_EXIT=7
  exec_case
  PROBE_EXIT=0
  if [ "$entry_exit" -eq 7 ]; then
    pass "[$label] F: propagates the requested command's exit status (7)"
  else
    fail "[$label] F: expected exit 7, got $entry_exit"
  fi
  expected_argv="--alpha beta two gamma"
  actual_argv="$(cat "$case_dir/marker.txt" 2>/dev/null || true)"
  if [ "$actual_argv" = "$expected_argv" ]; then
    pass "[$label] F: passes the requested command argv through exec unchanged"
  else
    fail "[$label] F: argv not preserved: ${actual_argv:-<missing>}"
  fi
}

run_root_branch_cases() {
  # Root-only bridge/trust diagnostics, shared by both generated
  # entrypoints; the identity is simulated through the fake id because the
  # branch makes no privileged host calls (socat and update-ca-certificates
  # are fixture-injected).

  # ── Case D: simulated root, host socket + CA — trust and dev-owned bridge
  setup_case D
  make_socket "$host_sock"
  printf '%s\n' '-----BEGIN FAKE ROOT CA-----' >"$mkcert_ca"
  FAKE_ID_UID=0
  exec_case
  FAKE_ID_UID=
  if command_ran; then
    pass "[$label] D: reaches the requested command on the root bridge/trust branch"
  else
    fail "[$label] D: expected the requested command to run, got exit $entry_exit"
  fi
  if grep -Fq 'mkcert root CA installed into system trust store' "$log_path"; then
    pass "[$label] D: records the mkcert CA install"
  else
    fail "[$label] D: mkcert CA install not recorded in the log"
  fi
  if [ -s "$case_dir/fake-update-ca.log" ]; then
    pass "[$label] D: invokes update-ca-certificates when a CA is present"
  else
    fail "[$label] D: update-ca-certificates never invoked despite a present CA"
  fi
  if grep -Fq 'host_sock present at' "$log_path"; then
    pass "[$label] D: records the host socket"
  else
    fail "[$label] D: host socket not recorded in the log"
  fi
  if grep -Fq 'socat pid=' "$log_path"; then
    pass "[$label] D: starts the bridge and records its pid"
  else
    fail "[$label] D: bridge start not recorded in the log"
  fi
  if [ -S "$bridge_sock" ]; then
    pass "[$label] D: bridge socket exists as a socket"
  else
    fail "[$label] D: bridge socket is not a socket"
  fi
  if grep -Eq 'user=[0-9]+,group=[0-9]+,mode=0600' "$case_dir/fake-socat.log"; then
    pass "[$label] D: root bridge is created dev-owned with mode 0600"
  else
    fail "[$label] D: root bridge socat invocation lacks user/group/mode=0600 policy"
  fi

  # ── Case E: simulated root, update-ca-certificates fails ─────────────
  setup_case E
  make_socket "$host_sock"
  printf '%s\n' '-----BEGIN FAKE ROOT CA-----' >"$mkcert_ca"
  FAKE_ID_UID=0
  FAKE_UPDATE_CA_EXIT=1
  exec_case
  FAKE_UPDATE_CA_EXIT=0
  FAKE_ID_UID=
  if command_ran; then
    pass "[$label] E: still reaches the requested command when trust setup fails"
  else
    fail "[$label] E: trust setup failure killed startup, exit $entry_exit"
  fi
  if grep -Fq 'WARNING update-ca-certificates failed' "$log_path"; then
    pass "[$label] E: reports the trust setup failure honestly"
  else
    fail "[$label] E: trust setup failure not reported in the log"
  fi
  if grep -Fq 'mkcert root CA installed into system trust store' "$log_path"; then
    fail "[$label] E: claims the CA was installed although update failed"
  else
    pass "[$label] E: makes no false CA claim"
  fi
}

run_php_fpm_nonroot_refusal_case() {
  # php-fpm's non-root branch must refuse root-owned PHP secrets/msmtp
  # initialization honestly (workspace-rust-bun has no such branch).
  setup_case P
  exec_case
  if command_ran; then
    pass "[$label] P: reaches the requested command without root-owned PHP setup"
  else
    fail "[$label] P: expected the requested command to run, got exit $entry_exit"
  fi
  if grep -Fq 'WARNING non-root startup cannot initialize root-owned PHP secrets' "$log_path"; then
    pass "[$label] P: honestly reports the PHP secrets/msmtp refusal"
  else
    fail "[$label] P: missing the honest non-root PHP secrets refusal"
  fi
}

# ── Run the matrix for every catalog ──────────────────────────────────

for dockerfile in "${DOCKERFILES[@]}"; do
  generate_entrypoint "$dockerfile"
  note "── $label ──"
  run_common_cases
  if [ "$label" = "workspace-rust-bun" ]; then
    run_root_branch_cases
  else
    note "NOTE: [$label] root-only PHP secrets/msmtp initialization needs container-only paths;"
    note "NOTE: it is exercised by the pack repository's scripts/catalog_pack_entrypoint_check.py."
    run_php_fpm_nonroot_refusal_case
  fi
  note ""
done

# ── Summary ───────────────────────────────────────────────────────────
note "Summary: $passes passed, $failures failed"
[ "$failures" -eq 0 ] || exit 1
exit 0
