mod attention_markers;
mod command;
mod comment_ratio;
mod conflicts;
mod contracts;
mod duplicate_blocks;
mod environment;
mod explain;
mod finding_templates;
mod generated_assets;
mod generated_in_src;
mod god_files;
mod health;
mod manifest;
mod progress;
mod references;
mod render;
mod render_support;
mod report;
mod run;
mod scan_checks;
mod stale_suppressions;
mod task_graph;
mod text_blocks;

pub(super) use command::run_doctor;
