use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde::Serialize;

use super::{
    manifest::{ManifestAttentionMarkersConfig, ManifestGeneratedAssetsConfig},
    LoadedCatalog, ManifestGodFilesConfig, ManifestScanOutputFormat, RunnerError, TaskManifest,
    TASK_MANIFEST_FILE,
};

#[path = "scan/options.rs"]
mod options;
#[path = "scan/render.rs"]
mod render;
#[path = "scan/support.rs"]
mod support;

pub(in crate::runner) use options::{
    catalog_scan_roots, doctor_attention_marker_options, doctor_generated_asset_options,
    doctor_god_file_options, load_root_attention_marker_options, load_root_generated_asset_options,
    load_root_god_file_options,
};
pub(in crate::runner) use render::{
    render_attention_marker_markdown, render_attention_marker_text,
    render_generated_asset_markdown, render_generated_asset_text, render_god_file_markdown,
    render_god_file_text,
};
use support::{
    attention_marker_category, attention_marker_matches_line, attention_marker_severity_rank,
    classify_generated_asset_severity, classify_severity, compile_attention_marker_patterns,
    count_code_lines, generated_asset_reason, generated_asset_severity_rank, is_generated_artifact,
    read_asset_sample, rebase_finding_path, severity_rank, should_skip_generated_asset_path,
    should_skip_path, trim_snippet, walk_scan_files, workspace_scan_roots,
};

pub(super) const DEFAULT_GOD_FILES_WARN: usize = 250;
pub(super) const DEFAULT_GOD_FILES_HIGH: usize = 400;
pub(super) const DEFAULT_GOD_FILES_CRITICAL: usize = 700;
pub(super) const DEFAULT_GENERATED_ASSETS_WARN_BYTES: usize = 1_000_000;
pub(super) const DEFAULT_GENERATED_ASSETS_HIGH_BYTES: usize = 5_000_000;
pub(super) const DEFAULT_GENERATED_ASSETS_CRITICAL_BYTES: usize = 20_000_000;
pub(super) const DEFAULT_ATTENTION_MARKER_WARNING: &[&str] = &[
    "TODO",
    "@TODO",
    "REVIEW",
    "NOTE",
    "placeholder",
    "later",
    "stub",
];
pub(super) const DEFAULT_ATTENTION_MARKER_HIGH: &[&str] = &[
    "FIXME",
    "XXX",
    "HACK",
    "@deprecated",
    "deprecated",
    "workaround",
    "tech debt",
];
pub(super) const DEFAULT_ATTENTION_MARKER_CRITICAL: &[&str] =
    &["BUG", "SECURITY", "remove before release"];

const DEFAULT_EXCLUDED_DIRS: &[&str] = &[
    ".git",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".yarn",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "target",
    "vendor",
];

const DEFAULT_DOC_DIRS: &[&str] = &["doc", "docs", "documentation"];

const DEFAULT_DATA_DIRS: &[&str] = &[
    "benchmark",
    "benchmarks",
    "benches",
    "example",
    "examples",
    "fixture",
    "fixtures",
    "migration",
    "migrations",
    "migrations_dev",
    "seeds",
];

const DEFAULT_LOCK_FILE_NAMES: &[&str] = &[
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "cargo.lock",
    "bun.lock",
    "bun.lockb",
    "composer.lock",
];

const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "auto-generated",
    "autogenerated",
    "code generated",
    "do not edit",
    "generated by",
];

const GENERATED_ASSET_DIRS: &[&str] = &[
    ".next",
    ".nuxt",
    ".parcel-cache",
    ".svelte-kit",
    ".turbo",
    "build",
    "coverage",
    "dist",
    "generated",
    "gen",
    "storybook-static",
    "third_party",
    "vendor",
    "vendors",
];

const GENERATED_ASSET_NAME_MARKERS: &[&str] =
    &[".bundle.", ".chunk.", ".generated.", ".map", ".min."];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum ScanRenderFormat {
    Text,
    Markdown,
}

impl ScanRenderFormat {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Text => "text",
            Self::Markdown => "markdown",
        }
    }
}

impl From<ManifestScanOutputFormat> for ScanRenderFormat {
    fn from(value: ManifestScanOutputFormat) -> Self {
        match value {
            ManifestScanOutputFormat::Text => Self::Text,
            ManifestScanOutputFormat::Markdown => Self::Markdown,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub(super) enum GodFileSeverity {
    Warning,
    High,
    Critical,
}

impl GodFileSeverity {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Warning => "warning",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct GodFileFinding {
    pub(super) path: String,
    pub(super) code_lines: usize,
    pub(super) total_lines: usize,
    pub(super) severity: GodFileSeverity,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct GodFileThresholds {
    pub(super) warn: usize,
    pub(super) high: usize,
    pub(super) critical: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct GodFileScanResult {
    pub(super) root: String,
    pub(super) scanned_files: usize,
    pub(super) skipped_generated: usize,
    pub(super) findings: Vec<GodFileFinding>,
    pub(super) thresholds: GodFileThresholds,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub(super) enum GeneratedAssetSeverity {
    Warning,
    High,
    Critical,
}

impl GeneratedAssetSeverity {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Warning => "warning",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct GeneratedAssetFinding {
    pub(super) path: String,
    pub(super) bytes: usize,
    pub(super) severity: GeneratedAssetSeverity,
    pub(super) reason: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct GeneratedAssetThresholds {
    pub(super) warn: usize,
    pub(super) high: usize,
    pub(super) critical: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct GeneratedAssetScanResult {
    pub(super) root: String,
    pub(super) scanned_files: usize,
    pub(super) candidate_files: usize,
    pub(super) findings: Vec<GeneratedAssetFinding>,
    pub(super) thresholds: GeneratedAssetThresholds,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub(super) enum AttentionMarkerCategory {
    DeferredWork,
    Deprecation,
    TemporaryArtifact,
}

impl AttentionMarkerCategory {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::DeferredWork => "deferred-work",
            Self::Deprecation => "deprecation",
            Self::TemporaryArtifact => "temporary-artifact",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub(super) enum AttentionMarkerSeverity {
    Warning,
    High,
    Critical,
}

impl AttentionMarkerSeverity {
    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::Warning => "warning",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct AttentionMarkerFinding {
    pub(super) path: String,
    pub(super) line: usize,
    pub(super) category: AttentionMarkerCategory,
    pub(super) severity: AttentionMarkerSeverity,
    pub(super) marker: String,
    pub(super) snippet: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct AttentionMarkerPatterns {
    pub(super) warning: Vec<String>,
    pub(super) high: Vec<String>,
    pub(super) critical: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct AttentionMarkerScanResult {
    pub(super) root: String,
    pub(super) scanned_files: usize,
    pub(super) matched_lines: usize,
    pub(super) findings: Vec<AttentionMarkerFinding>,
    pub(super) patterns: AttentionMarkerPatterns,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct TextRenderOptions {
    pub(super) show_warnings: bool,
}

#[derive(Debug, Clone)]
pub(super) struct GodFileScanOptions {
    pub(super) thresholds: GodFileThresholds,
    pub(super) fail_on_findings: bool,
    pub(super) respect_gitignore: bool,
    pub(super) doctor_enabled: bool,
    pub(super) include: Vec<String>,
    pub(super) exclude: Vec<String>,
    pub(super) format: ScanRenderFormat,
    pub(super) out: Option<String>,
}

#[derive(Debug, Clone)]
pub(super) struct GeneratedAssetScanOptions {
    pub(super) thresholds: GeneratedAssetThresholds,
    pub(super) fail_on_findings: bool,
    pub(super) respect_gitignore: bool,
    pub(super) doctor_enabled: bool,
    pub(super) include: Vec<String>,
    pub(super) exclude: Vec<String>,
    pub(super) format: ScanRenderFormat,
    pub(super) out: Option<String>,
}

#[derive(Debug, Clone)]
pub(super) struct AttentionMarkerScanOptions {
    pub(super) patterns: AttentionMarkerPatterns,
    pub(super) fail_on_findings: bool,
    pub(super) respect_gitignore: bool,
    pub(super) doctor_enabled: bool,
    pub(super) include: Vec<String>,
    pub(super) exclude: Vec<String>,
    pub(super) format: ScanRenderFormat,
    pub(super) out: Option<String>,
}

pub(super) fn run_god_file_scan_workspace(
    target_root: &Path,
    scan_roots: &[PathBuf],
    options: &GodFileScanOptions,
) -> Result<GodFileScanResult, RunnerError> {
    let mut findings = Vec::<GodFileFinding>::new();
    let mut scanned_files = 0usize;
    let mut skipped_generated = 0usize;

    for (root, skipped_roots) in workspace_scan_roots(target_root, scan_roots) {
        let result = run_god_file_scan_single(&root, &skipped_roots, options)?;
        scanned_files += result.scanned_files;
        skipped_generated += result.skipped_generated;
        findings.extend(result.findings.into_iter().map(|mut finding| {
            finding.path = rebase_finding_path(target_root, &root, &finding.path);
            finding
        }));
    }

    findings.sort_by(|left, right| {
        severity_rank(right.severity)
            .cmp(&severity_rank(left.severity))
            .then_with(|| right.code_lines.cmp(&left.code_lines))
            .then_with(|| left.path.cmp(&right.path))
    });

    Ok(GodFileScanResult {
        root: target_root.display().to_string(),
        scanned_files,
        skipped_generated,
        findings,
        thresholds: options.thresholds.clone(),
    })
}

fn run_god_file_scan_single(
    root: &Path,
    skipped_roots: &[PathBuf],
    options: &GodFileScanOptions,
) -> Result<GodFileScanResult, RunnerError> {
    options.validate()?;
    let mut findings = Vec::<GodFileFinding>::new();
    let mut scanned_files = 0usize;
    let mut skipped_generated = 0usize;
    walk_scan_files(
        root,
        skipped_roots,
        options.respect_gitignore,
        &options.include,
        &options.exclude,
        should_skip_path,
        |path, rel, rel_str| {
            let contents = std::fs::read_to_string(path).map_err(|error| {
                RunnerError::task_invocation(format!(
                    "scan read failed for {}: {error}",
                    path.display()
                ))
            })?;
            if is_generated_artifact(rel, &contents) {
                skipped_generated += 1;
                return Ok(());
            }

            let code_lines = count_code_lines(rel, &contents);
            scanned_files += 1;
            let severity = classify_severity(code_lines, &options.thresholds);
            if let Some(severity) = severity {
                findings.push(GodFileFinding {
                    path: rel_str.to_owned(),
                    code_lines,
                    total_lines: contents.lines().count(),
                    severity,
                });
            }
            Ok(())
        },
    )?;

    findings.sort_by(|left, right| {
        severity_rank(right.severity)
            .cmp(&severity_rank(left.severity))
            .then_with(|| right.code_lines.cmp(&left.code_lines))
            .then_with(|| left.path.cmp(&right.path))
    });

    Ok(GodFileScanResult {
        root: root.display().to_string(),
        scanned_files,
        skipped_generated,
        findings,
        thresholds: options.thresholds.clone(),
    })
}

pub(super) fn run_generated_asset_scan_workspace(
    target_root: &Path,
    scan_roots: &[PathBuf],
    options: &GeneratedAssetScanOptions,
) -> Result<GeneratedAssetScanResult, RunnerError> {
    let mut findings = Vec::<GeneratedAssetFinding>::new();
    let mut scanned_files = 0usize;
    let mut candidate_files = 0usize;

    for (root, skipped_roots) in workspace_scan_roots(target_root, scan_roots) {
        let result = run_generated_asset_scan_single(&root, &skipped_roots, options)?;
        scanned_files += result.scanned_files;
        candidate_files += result.candidate_files;
        findings.extend(result.findings.into_iter().map(|mut finding| {
            finding.path = rebase_finding_path(target_root, &root, &finding.path);
            finding
        }));
    }

    findings.sort_by(|left, right| {
        generated_asset_severity_rank(right.severity)
            .cmp(&generated_asset_severity_rank(left.severity))
            .then_with(|| right.bytes.cmp(&left.bytes))
            .then_with(|| left.path.cmp(&right.path))
    });

    Ok(GeneratedAssetScanResult {
        root: target_root.display().to_string(),
        scanned_files,
        candidate_files,
        findings,
        thresholds: options.thresholds.clone(),
    })
}

fn run_generated_asset_scan_single(
    root: &Path,
    skipped_roots: &[PathBuf],
    options: &GeneratedAssetScanOptions,
) -> Result<GeneratedAssetScanResult, RunnerError> {
    options.validate()?;
    let mut findings = Vec::<GeneratedAssetFinding>::new();
    let mut scanned_files = 0usize;
    let mut candidate_files = 0usize;
    walk_scan_files(
        root,
        skipped_roots,
        options.respect_gitignore,
        &options.include,
        &options.exclude,
        should_skip_generated_asset_path,
        |path, rel, rel_str| {
            let bytes = std::fs::metadata(path)
                .map_err(|error| {
                    RunnerError::task_invocation(format!(
                        "scan metadata failed for {}: {error}",
                        path.display()
                    ))
                })?
                .len() as usize;
            let sample = read_asset_sample(path)?;
            scanned_files += 1;
            let reason = match generated_asset_reason(rel, &sample) {
                Some(reason) => reason,
                None => return Ok(()),
            };
            candidate_files += 1;

            let severity = classify_generated_asset_severity(bytes, &options.thresholds);
            if let Some(severity) = severity {
                findings.push(GeneratedAssetFinding {
                    path: rel_str.to_owned(),
                    bytes,
                    severity,
                    reason,
                });
            }
            Ok(())
        },
    )?;

    findings.sort_by(|left, right| {
        generated_asset_severity_rank(right.severity)
            .cmp(&generated_asset_severity_rank(left.severity))
            .then_with(|| right.bytes.cmp(&left.bytes))
            .then_with(|| left.path.cmp(&right.path))
    });

    Ok(GeneratedAssetScanResult {
        root: root.display().to_string(),
        scanned_files,
        candidate_files,
        findings,
        thresholds: options.thresholds.clone(),
    })
}

pub(super) fn run_attention_marker_scan_workspace(
    target_root: &Path,
    scan_roots: &[PathBuf],
    options: &AttentionMarkerScanOptions,
) -> Result<AttentionMarkerScanResult, RunnerError> {
    let mut findings = Vec::<AttentionMarkerFinding>::new();
    let mut scanned_files = 0usize;
    let mut matched_lines = 0usize;

    for (root, skipped_roots) in workspace_scan_roots(target_root, scan_roots) {
        let result = run_attention_marker_scan_single(&root, &skipped_roots, options)?;
        scanned_files += result.scanned_files;
        matched_lines += result.matched_lines;
        findings.extend(result.findings.into_iter().map(|mut finding| {
            finding.path = rebase_finding_path(target_root, &root, &finding.path);
            finding
        }));
    }

    findings.sort_by(|left, right| {
        attention_marker_severity_rank(right.severity)
            .cmp(&attention_marker_severity_rank(left.severity))
            .then_with(|| left.path.cmp(&right.path))
            .then_with(|| left.line.cmp(&right.line))
            .then_with(|| left.marker.cmp(&right.marker))
    });

    Ok(AttentionMarkerScanResult {
        root: target_root.display().to_string(),
        scanned_files,
        matched_lines,
        findings,
        patterns: options.patterns.clone(),
    })
}

fn run_attention_marker_scan_single(
    root: &Path,
    skipped_roots: &[PathBuf],
    options: &AttentionMarkerScanOptions,
) -> Result<AttentionMarkerScanResult, RunnerError> {
    options.validate()?;
    let patterns = compile_attention_marker_patterns(&options.patterns);
    let mut findings = Vec::<AttentionMarkerFinding>::new();
    let mut scanned_files = 0usize;
    let mut matched_lines = 0usize;

    walk_scan_files(
        root,
        skipped_roots,
        options.respect_gitignore,
        &options.include,
        &options.exclude,
        should_skip_path,
        |path, rel, rel_str| {
            let contents = std::fs::read_to_string(path).map_err(|error| {
                RunnerError::task_invocation(format!(
                    "scan read failed for {}: {error}",
                    path.display()
                ))
            })?;
            if is_generated_artifact(rel, &contents) {
                return Ok(());
            }

            scanned_files += 1;
            for (line_number, raw_line) in contents.lines().enumerate() {
                let line = raw_line.trim();
                if line.is_empty() {
                    continue;
                }
                let mut line_has_match = false;
                let mut matched_keys = BTreeSet::<String>::new();
                for (severity, marker, marker_lower) in &patterns {
                    if !attention_marker_matches_line(raw_line, marker_lower) {
                        continue;
                    }
                    let dedupe_key = marker_lower.trim_start_matches('@').to_owned();
                    if !matched_keys.insert(dedupe_key) {
                        continue;
                    }
                    line_has_match = true;
                    findings.push(AttentionMarkerFinding {
                        path: rel_str.to_owned(),
                        line: line_number + 1,
                        category: attention_marker_category(marker_lower),
                        severity: *severity,
                        marker: marker.clone(),
                        snippet: trim_snippet(line, 120),
                    });
                }
                if line_has_match {
                    matched_lines += 1;
                }
            }
            Ok(())
        },
    )?;

    findings.sort_by(|left, right| {
        attention_marker_severity_rank(right.severity)
            .cmp(&attention_marker_severity_rank(left.severity))
            .then_with(|| left.path.cmp(&right.path))
            .then_with(|| left.line.cmp(&right.line))
            .then_with(|| left.marker.cmp(&right.marker))
    });

    Ok(AttentionMarkerScanResult {
        root: root.display().to_string(),
        scanned_files,
        matched_lines,
        findings,
        patterns: options.patterns.clone(),
    })
}

pub(super) fn format_bytes(bytes: usize) -> String {
    if bytes >= 1_000_000_000 {
        return format!("{:.1} GB", bytes as f64 / 1_000_000_000f64);
    }
    if bytes >= 1_000_000 {
        return format!("{:.1} MB", bytes as f64 / 1_000_000f64);
    }
    if bytes >= 1_000 {
        return format!("{:.1} KB", bytes as f64 / 1_000f64);
    }
    format!("{bytes} B")
}

#[cfg(test)]
#[path = "scan/tests.rs"]
mod tests;
